version: '3'
services:
  zookernel:
    platform: linux/amd64
    image: geolabs/mapmint:latest
    ports:
      - "80:80"
    volumes:
      - ./mapmint/docker/main.cfg:/usr/lib/cgi-bin/main.cfg
      - ./docker/oas.cfg:/usr/lib/cgi-bin/oas.cfg
      - ./mapmint/docker/default.conf:/etc/apache2/sites-available/000-default.conf
      - ./zoo-project/zoo-services/echo-py/cgi-env/echo_service.py:/usr/lib/cgi-bin/echo_service.py
      - ./zoo-project/zoo-services/echo-py/cgi-env/echo.zcfg:/usr/lib/cgi-bin/echo.zcfg
      - ./zoo-project/zoo-services/utils/open-api/server/publish.py:/usr/lib/cgi-bin/publish.py
      - ./zoo-project/zoo-services/utils/open-api/server/subscriber.py:/usr/lib/cgi-bin/subscriber.py
      - ./docker/.htaccess:/var/www/html/.htaccess
      - ./zoo-project/zoo-services/utils/open-api/templates/index.html:/var/www/index.html
      - ./zoo-project/zoo-services/utils/open-api/static:/var/www/html/static
      - ./data/share:/usr/com/zoo-project/ftp/external
      - ./data/dirs:/usr/com/zoo-project/dirs
      - ./data/maps:/usr/com/zoo-project/maps
      - ./data/public_maps:/usr/com/zoo-project/public_maps
      - ./tmp:/tmp
      - ./tmp:/var/www/html/temp
    depends_on:
      - pgbouncer
      - redis
    environment:
      - ZOO_REDIS_HOST=redis
  libreoffice:
    platform: linux/amd64
    image: geolabs/libreoffice:latest
    #build:
    #  context: .
    #  dockerfile: mapmint/docker/stable/Dockerfile.lo
    volumes:
      - ./mapmint/template/data/ftp/templates/:/usr/com/zoo-project/ftp/templates
      - ./tmp:/var/www/html/temp
  websocketd:
    platform: linux/amd64
    build: ./docker/websocketd
    depends_on:
      - redis
    ports:
      - 8888:8888
    environment:
      - ZOO_REDIS_HOST=redis
    volumes:
      - ./zoo-project/zoo-services/utils/open-api/server/subscriber.py:/shell.py
    command: ["--port=8888", "/shell.py"]
  pg:
    platform: linux/amd64
    #For M1 users please build kartoza/postgis then uncomment the line below
    #image: docker.io/kartoza/postgis
    image: postgis/postgis:10-2.5-alpine
    restart: always
    environment:
      POSTGRES_USER: zoo
      POSTGRES_PASSWORD: zoo
      POSTGRES_DB: zoo
    volumes:
      # Load the zoo kernel schema
      - ./zoo-project/zoo-kernel/sql/schema.sql:/docker-entrypoint-initdb.d/11-schema.sql
      # Load the MapMint database and functions
      - ./mapmint/template/sql/mmdb.sql:/docker-entrypoint-initdb.d/12-mmdb.sql
      - ./mapmint/template/sql/indicators.sql:/docker-entrypoint-initdb.d/13-indicators.sql
      - ./mapmint/template/sql/tables.sql:/docker-entrypoint-initdb.d/14-tables.sql      
  pgbouncer:
    platform: linux/amd64
    image: edoburu/pgbouncer:1.8.1
    environment:
      DATABASE_URL: "postgres://zoo:zoo@pg/zoo"
      MAX_CLIENT_CONN: 1000
      MAX_DB_CONNECTIONS: 100
      DEFAULT_POOL_SIZE: 100
      POOL_MODE: transaction
    ports:
      - "5432:5432"
    depends_on:
      - pg
  redis:
    image: redis:6.0.9
