TROOT=$(ZOOK_DIR)\

!include $(ZOOK_DIR)\nmake.opt

cgi-env/service.zo: service.c
	$(CPP) -I$(ZOOK_DIR) -I$(XSLT_DIR)/ -I$(GDAL_DIR)/alg -I$(GDAL_DIR)/ogr/ogrsf_frmts -I$(ZOOK_DIR)/../../thirds/dirent-win32 /DZOO_SERVICE $(CFLAGS) /c service.c
	link /dll /out:cgi-env/service.zo $(ZOOK_DIR)/dirent.obj $(ZOOK_DIR)/service_internal.obj $(ZOOK_DIR)/service_internal_ms.obj $(ZOOK_DIR)/service_internal_js.obj $(ZOOK_DIR)/ulinet.obj ./service.obj $(LDFLAGS) 

clean:
	del cgi-env\service.zo
