TROOT=$(ZOOK_DIR)\

!include $(ZOOK_DIR)\nmake.opt

cgi-env/service.zo: service.c
	$(CPP) -I$(ZOOK_DIR) -I$(FT_DIR)/include -I$(FT_DIR)/include/freetype -I$(GDAL_DIR)/alg -I$(GDAL_DIR)/ogr/ogrsf_frmts -I$(ZOOK_DIR)/../../thirds/dirent-win32 $(CFLAGS) /c service.c
	link /dll /out:cgi-env/service.zo $(ZOOK_DIR)/libzoo_service.lib ./service.obj $(LDFLAGS) $(FT_DIR)\lib\freetype2411.lib

clean:
	del cgi-env\service.zo
